import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Legacy brand alias
        brand: { DEFAULT: '#004ac6', light: '#3b7de8', dark: '#003ea8' },
        // Stitch / Material Design 3 design system tokens
        primary: '#004ac6',
        secondary: '#505f76',
        tertiary: '#943700',
        error: '#ba1a1a',
        background: '#faf8ff',
        surface: '#faf8ff',
        'surface-bright': '#faf8ff',
        'surface-dim': '#d9d9e5',
        'surface-variant': '#e1e2ed',
        'surface-container': '#ededf9',
        'surface-container-low': '#f3f3fe',
        'surface-container-high': '#e7e7f3',
        'surface-container-highest': '#e1e2ed',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#0053db',
        outline: '#737686',
        'outline-variant': '#c3c6d7',
        'on-surface': '#191b23',
        'on-surface-variant': '#434655',
        'on-background': '#191b23',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'primary-container': '#2563eb',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        'on-primary-container': '#eeefff',
        'secondary-container': '#d0e1fb',
        'secondary-fixed': '#d3e4fe',
        'secondary-fixed-dim': '#b7c8e1',
        'on-secondary-fixed': '#0b1c30',
        'on-secondary-fixed-variant': '#38485d',
        'on-secondary-container': '#54647a',
        'tertiary-container': '#bc4800',
        'tertiary-fixed': '#ffdbcd',
        'tertiary-fixed-dim': '#ffb596',
        'on-tertiary-fixed': '#360f00',
        'on-tertiary-fixed-variant': '#7d2d00',
        'on-tertiary-container': '#ffede6',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'inverse-surface': '#2e3039',
        'inverse-on-surface': '#f0f0fb',
        'inverse-primary': '#b4c5ff',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'stack-xs': '4px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
        gutter: '24px',
        'sidebar-width': '240px',
        'container-max': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};

export default config;
