import { mkdirSync } from 'fs';
import { join } from 'path';
import type { Quote, Inquiry } from '@inbox-pilot/db';
import type { DraftQuoteResult } from '@inbox-pilot/agent';

function quoteHtml(quote: Quote, inquiry: Inquiry, draft: DraftQuoteResult): string {
  const items = (draft.lineItems ?? [])
    .map(
      (li: { sku: string; description: string; qty: number; unitPrice: number; total: number }) => `<tr>
        <td>${li.sku}</td>
        <td>${li.description}</td>
        <td style="text-align:center">${li.qty}</td>
        <td style="text-align:right">$${li.unitPrice.toFixed(2)}</td>
        <td style="text-align:right">$${li.total.toFixed(2)}</td>
      </tr>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<style>
  body { font-family: Arial, sans-serif; color: #222; padding: 40px; }
  h1 { color: #1a56db; }
  table { width: 100%; border-collapse: collapse; margin-top: 24px; }
  th { background: #1a56db; color: white; padding: 8px 12px; text-align: left; }
  td { padding: 8px 12px; border-bottom: 1px solid #eee; }
  .totals { margin-top: 16px; text-align: right; }
  .total-row { font-weight: bold; font-size: 1.1em; }
  .meta { color: #666; margin-bottom: 24px; }
  .footer { margin-top: 40px; font-size: 0.85em; color: #999; }
</style>
</head>
<body>
<h1>InboxPilot — Price Quote</h1>
<div class="meta">
  <strong>To:</strong> ${inquiry.fromName ?? inquiry.fromEmail}<br/>
  <strong>Email:</strong> ${inquiry.fromEmail}<br/>
  <strong>Quote Date:</strong> ${new Date().toLocaleDateString()}<br/>
  <strong>Valid Until:</strong> ${new Date(draft.validUntil).toLocaleDateString()}<br/>
  <strong>Quote ID:</strong> ${quote.id}
</div>
<table>
  <thead>
    <tr><th>SKU</th><th>Description</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr>
  </thead>
  <tbody>${items}</tbody>
</table>
<div class="totals">
  <div>Subtotal: $${Number(quote.subtotal).toFixed(2)}</div>
  <div>Tax (8%): $${Number(quote.tax).toFixed(2)}</div>
  <div class="total-row">Total: $${Number(quote.total).toFixed(2)} ${quote.currency}</div>
</div>
<p><strong>Terms:</strong> ${draft.terms}</p>
<div class="footer">Generated by InboxPilot &bull; Powered by Qwen AI</div>
</body>
</html>`;
}

export async function renderQuotePdf(
  quote: Quote,
  inquiry: Inquiry,
  draft: DraftQuoteResult,
): Promise<string> {
  const outputDir = process.env.PDF_OUTPUT_DIR ?? '/tmp/inbox-pilot/pdfs';
  mkdirSync(outputDir, { recursive: true });
  const outPath = join(outputDir, `quote-${quote.id}.pdf`);

  // Lazy-load puppeteer to avoid startup cost
  const puppeteer = await import('puppeteer');
  const browser = await puppeteer.default.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] });
  const page = await browser.newPage();
  await page.setContent(quoteHtml(quote, inquiry, draft), { waitUntil: 'networkidle0' });
  await page.pdf({ path: outPath, format: 'A4', printBackground: true, margin: { top: '20px', bottom: '20px', left: '20px', right: '20px' } });
  await browser.close();

  return outPath;
}
